### ISSUE TITLE
Warning on Unity 2022.3.11

### ISSUE THREAD

**Issue by laicasaane** [innogames/asset-relations-viewer#21]
I've just installed the package on Unity 2022.3.11 and see this warning everytime domain reload happens.

```
Method Com.Innogames.Core.Frontend.AssetRelationsViewer.AssetRelationsViewerWindow.ShowWindow has invalid parameters. MenuCommand is the only optional supported parameter.
—
at void UnityEngine.Debug.LogWarningFormat(string format, params object[] args)
bool UnityEditor.MenuService.ValidateMethodForMenuCommand(MethodInfo methodInfo)
void UnityEditor.MenuService.ExtractMenuItemsFromAttributes()+(MethodInfo m) => { }
MethodInfo[] System.Linq.Enumerable+WhereEnumerableIterator<System.Reflection.MethodInfo>.ToArray()
new System.Linq.Buffer<System.Reflection.MethodInfo>(IEnumerable<MethodInfo> source)
List<MethodInfo> System.Linq.OrderedEnumerable<System.Reflection.MethodInfo>.ToList()
List<MethodInfo> System.Linq.Enumerable.ToList<MethodInfo>(IEnumerable<MethodInfo> source)
void UnityEditor.MenuService.ExtractMenuItemsFromAttributes()
MenuItemScriptCommand[] UnityEditor.MenuService.GetMenuItemsFromAttributesById(string id)
MenuItemScriptCommand[] UnityEditor.MenuService.GetMenuItemsFromAttributes()
```

**Comment by pak762** [comment]
Thank you for reminding me about this warning. I created a new 1.5.2 release now where it is removed. Please let me know if this worked for you so I can close the ticket.

**Comment by laicasaane** [comment]
Oops, I'm actually using version 2.0.0-beta.

I've installed the package via OpenUPM and it's still stucked at 2.0.0-beta. You should change the version in package.json too so OpenUPM can pick up the newer tag.

![image](https://github.com/innogames/asset-relations-viewer/assets/1594982/5b7f837d-d74e-4ca2-8181-da546257c1ad)

**Comment by pak762** [comment]
My bad. I did not even know these 2.0.0 tags are visible on openupm since there was never a release on github for it. These where just planned for internal testing since not being merged to master yet. I will create a 3.0.0-pre.1 version (due to many api changes) and from now on properly update the version in the package.json as well since I did not know this causes confusion on openupm.

The version should be ready tomorrow.

Note that this now includes the Addressables Addon so the additional repo is not required any longer after 3.0.0.

**Comment by laicasaane** [comment]
Thanks!

> since there was never a release on github for it

OpenUPM reads the tags, not the release though.

**Comment by pak762** [comment]
In the meantime I created a new 3.0.0-pre.1 and also 3.0.0-pre.2 tag

Please let me know if everything works for you

**Comment by laicasaane** [comment]
Thanks! I don't see warnings anymore.
